const WORD_PAIRS = [
  ['Pizza', 'Flatbread'],
  ['Ocean', 'Sea'],
  ['Guitar', 'Ukulele'],
  ['Castle', 'Fortress'],
  ['Lion', 'Tiger'],
  ['Sushi', 'Sashimi'],
  ['Astronaut', 'Cosmonaut'],
  ['Vampire', 'Zombie'],
  ['Laptop', 'Tablet'],
  ['Coffee', 'Tea'],
  ['Shark', 'Dolphin'],
  ['Sword', 'Knife'],
  ['Doctor', 'Nurse'],
  ['Prison', 'School'],
  ['Batman', 'Superman'],
  ['Helicopter', 'Drone'],
  ['Snake', 'Lizard'],
  ['Perfume', 'Deodorant'],
  ['Mansion', 'Villa'],
  ['Passport', 'ID Card'],
  ['Spy', 'Detective'],
  ['Ghost', 'Shadow'],
  ['Hacker', 'Programmer'],
  ['Stadium', 'Arena'],
  ['Diamond', 'Crystal'],
  ['Poison', 'Medicine'],
  ['Throne', 'Chair'],
  ['Sniper', 'Archer'],
  ['Explosion', 'Firework'],
  ['Tunnel', 'Cave'],
  ['Disguise', 'Costume'],
  ['Signal', 'Message'],
  ['Hostage', 'Prisoner'],
  ['Target', 'Victim'],
  ['Blackout', 'Eclipse'],
  ['Decoy', 'Dummy'],
  ['Alias', 'Nickname'],
  ['Cipher', 'Code'],
  ['Extraction', 'Escape'],
  ['Fingerprint', 'DNA'],
  ['Bounty', 'Reward'],
  ['Safehouse', 'Bunker'],
  ['Interrogation', 'Interview'],
  ['Surveillance', 'Stalking'],
  ['Warhead', 'Bomb'],
  ['Defector', 'Traitor'],
  ['Handler', 'Manager'],
  ['Burn Notice', 'Pink Slip'],
  ['Sleeper', 'Spy'],
  ['Dossier', 'Resume'],
]

export function pickWordPair() {
  const pair = WORD_PAIRS[Math.floor(Math.random() * WORD_PAIRS.length)]
  // Randomly swap asset/ghost word
  const swapped = Math.random() < 0.5
  return {
    assetWord: swapped ? pair[1] : pair[0],
    ghostWord: swapped ? pair[0] : pair[1],
  }
}
